### ISSUE TITLE
Glimmer2 Compatibility

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/ember-let#14]
Ember let test suite should pass against glimmer enabled ember, but falls over.

https://travis-ci.org/thefrontside/ember-let/jobs/156027764

**Comment by rwjblue** [comment]
I've got a spike on this, though I'm unsure how I feel about it 😝

**Comment by mitchlloyd** [comment]
I'm just going to drop this here. Please don't tell any Ember core team members about it. https://ember-twiddle.com/16243ed7e17b2cc5bb57b4322aa1ed71?openFiles=templates.application.hbs%2C

**Comment by rwjblue** [comment]
Haha, indeed I am aware 😉 

It still has the super unexpected issues of not rendering the block if you happen to use something that evaluates to falsey (`false`, `undefined`, `null`, `[]`, etc) in the template.  That is actually pretty surprising to most folks these days.

Honestly, I am pretty excited about the newer inline form.  I want to continue experimenting then convince @cowboyd to write an RFC to make it part of Ember... 😈

**Comment by rwjblue** [comment]
FWIW, I have a pretty gnarly spike on fixing this in canary/alpha builds with Glimmer but it is pretty annoying. I tried to do some cleanup in a recent Ember PR to make this a bit easier/nicer.

**Comment by mitchlloyd** [comment]
Ah yes, not rendering the block when the first value is falsey definitely makes that a non-starter.
