### ISSUE TITLE
Badges! and other assorted OSS goodness

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/ember-let#3]
@Robdel12 put together a checklist somewhere of what an FS OSS repo should be. I can't find it, but it should probably be linked from the oss-wumbo README.

Seems like once we nail these, we can remove the WIP tag.

**Comment by Robdel12** [comment]
https://github.com/thefrontside/oss-wumbo/issues/4 shabam

**Comment by Robdel12** [comment]
This was closed with #4!
