### ISSUE TITLE
Not working after upgrade to Ember 2.10.0

### ISSUE THREAD

**Issue by jurgenwerk** [thefrontside/ember-let#31]
### Ember Version / Ember CLI Version:

**Ember Version:** 2.10.0
**Ember CLI Version:** 2.10.0-beta.2

### Expected Behavior

Before I updated (from Ember 2.7.0), the `{{let}}` helper worked OK.

### Actual Behavior

After upgrade to Ember 2.10.0, `{{let}}` helpers are throwing this error:

```
Uncaught TypeError: args.evaluate is not a function(…)
```

### Steps To Reproduce:
1. Simply writing `{{let test="test"}}` throws said error in my app. I wanted to reproduce in Twiddle, but sadly it doesn't support 2.10.0.

**Comment by ming-codes** [comment]
I have the same issue. I'm on Ember canary.

**Comment by Robdel12** [comment]
@rwjblue / @mmun will have better insight than I will :) I'm going to have to guess it's something with the AST transform that we're doing?

**Comment by jurgenwerk** [comment]
Thanks for fixing! <3
