### ISSUE TITLE
Uncaught Error: Could not find module glimmer-runtime

### ISSUE THREAD

**Issue by ming-codes** [thefrontside/ember-let#35]
### Version of ember-let:

0.5.4

### Ember Version / Ember CLI Version:

**Ember Version:**

2.13.0-beta.1

**Ember CLI Version:**

### Expected Behavior

Not throw error

### Actual Behavior

Thrown error

### Steps To Reproduce:

Just run ember-let with `2.13.0-beta.1` should be enough to produce the error.

I believe `glimmer-runtime` no longer exist in 2.13

https://github.com/thefrontside/ember-let/blob/e1e3f0d9e2305f09dc72764ed3414714c36b844f/vendor/ember-let/register.js#L8

### Ember Twiddle / Example repo / Failing test:

https://travis-ci.org/ming-codes/ember-ui-kit/jobs/211936752

**Comment by Robdel12** [comment]
Pinging @rwjblue. 

I tried to clone ember-ui-kit and run the current beta but the project doesn't build. :/

**Comment by ming-codes** [comment]
Travis builds just fine https://travis-ci.org/ming-codes/ember-ui-kit

Other than beta that's giving this error.

Are you using ember-try?

**Comment by Robdel12** [comment]
Hm, looks like ember-try is using bower and your bower.json file is empty. I was changing `ember-source` to beta and getting a build error. 
![image](https://cloud.githubusercontent.com/assets/2072894/24025673/d6584b36-0a89-11e7-8b7f-154f36f1c911.png)

**Comment by ming-codes** [comment]
#36 is a duplicate of this one, but it's getting a lot of attention. I'll close this.
