### ISSUE TITLE
Fails with ember 2.15 due to @glimmer/runtime change

### ISSUE THREAD

**Issue by kturney** [thefrontside/ember-let#44]
### Ember Version / Ember CLI Version:

**Ember Version:** 2.15.0
**Ember CLI Version:** 2.15.0

### Expected Behavior

ember-let should still work

### Actual Behavior

ember-let blows up with
```
TypeError: compileArgs is not a function
    at register.js:33
    at Blocks.compile (runtime.js:4415)
    at runtime.js:4067
    at Compilers.compile (runtime.js:3958)
    at compileStatement (runtime.js:4714)
    at compileStatements (runtime.js:4719)
    at CompilableTemplate.compileStatic (runtime.js:4744)
    at runtime.js:845
    at AppendOpcodes.evaluate (runtime.js:70)
    at VM.next (runtime.js:7244)
```

It seems the @glimmer/runtime API used at https://github.com/thefrontside/ember-let/blob/b26eeb279b4c4d0384456e2127a03c9c553e5d52/addon/register.js#L13 has changed.

### Steps To Reproduce:
1. upgrade to ember 2.15

### Ember Twiddle / Example repo / Failing test:

I tried to make a twiddle but looks like ember 2.15 isn't supported yet.

**Comment by kturney** [comment]
oh. looks like this is fixed by https://github.com/thefrontside/ember-let/pull/43

**Comment by HeroicEric** [comment]
This should be fixed by https://github.com/thefrontside/ember-let/pull/45
