### ISSUE TITLE
Proposal: inline let

### ISSUE THREAD

**Issue by taras** [thefrontside/ember-let#7]
I had an idea recently of how we could create an inline version of `let` helper that'd automatically update a variable when calculation changes.

For example,

``` hbs
{{let hello "world"}}
{{hello}}
```

Would output "world".

This value would also be reactive, so it'll automatically update the variable binding when calculation changes.

``` hbs
{{let greeting (concat "hello " to)}}

{{greeting}}

<button {{action (mut to) "world"}}>To world</button>
```

Would output "hello " first, on click of button would set `to` to "world" and render "hello world".

I can be useful to define variables that apply to the entire template without introducing nesting and to define reactive variables that change based on computation.

**Comment by cowboyd** [comment]
I'm curious about scoping. What happens if I say:

``` hbs
{{let num 0}}

num = {{num}}

{{#each (list 1 2 3) as |num|}}
  num = {{num}}
{{/each}}

num = {{num}}
```

I'd expect to see:

```
num = 0
num = 1
num = 2
num = 3
num = 0
```

Would it also work with explicit let's in block scope?

``` hbs
{{let num 0}}

num = {{num}}

{{#each (list 1 2 3) as |int|}}
  {{let num int}}
  num = {{num}}
{{/each}}

num = {{num}}
```

**Comment by taras** [comment]
It does not do anything to resolve the path. It will only effect the path that's passed to it.

This will be a good thing to verify with tests. I'll add these to confirm my assumptions.

**Comment by cowboyd** [comment]
Any thoughts about multiple binding expressions as per `let` in most LISP implementations?

http://docs.racket-lang.org/reference/let.html#(form._((lib._racket/private/letstx-scheme..rkt)._let))

``` hbs
{{let height (subtract top bottom) width (subtract right left)}}
```

**Comment by cowboyd** [comment]
This is probably a better link for binding in Scheme http://docs.racket-lang.org/guide/let.html

**Comment by taras** [comment]
Multiple binding expressions seem like a great idea and should be easy to implement.

Unfortunately, when one value changes, all of the binding vales will be reapplied but that might not be a problem considering that glimmer is smart about caching the updates.

**Comment by taras** [comment]
> I'm curious about scoping.

The scoping test was successful. Got exactly what you(and I) expected. 

> Would it also work with explicit let's in block scope?

No, this actually seems to cause an infinite loop. Ember throws a warning that `{{num}}` was modified multiple times in single run loop.

**Comment by taras** [comment]
@cowboyd just added multiple declarations support

**Comment by taras** [comment]
I need to provide feedback in case the user messed up the order and specified value where path should be.

**Comment by cowboyd** [comment]
One question: for multiple binding assignments, are previous binding expressions visible in subsequent ones? E.g.

``` hbs
{{#let height (subtract top bottom) width (subtract right left) area (multiply height width)}}
```

Not sure if it should or shouldn't be, or even what's possible, but I think it's important to ascertain which one it is.

**Comment by taras** [comment]
@cowboyd it does allow to be used in consequent assignments. I have a test for this scenario

**Comment by taras** [comment]
I haven't tried anything as collect as your example but I can try in an integration test

**Comment by taras** [comment]
*complex
